name: Enable user notifications

on:
  workflow_dispatch:
    inputs:
      email:
        required: true
        type: string
      username:
        required: true
        type: string
      alias:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo-b
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Debug vars
        run: |
          echo "EMAIL=${{ github.event.inputs.email }}"
          echo "USERNAME=${{ github.event.inputs.username }}"
          echo "ALIAS=${{ github.event.inputs.alias }}"

      - name: Update notifications.yaml
        run: |
          EMAIL="${{ github.event.inputs.email }}"
          USERNAME="${{ github.event.inputs.username }}"
          ALIAS="${{ github.event.inputs.alias }}"

          echo "Adding $USERNAME to notifications.yaml"

          FILE="notifications/notifications.yaml"

          # Add user with correct structure
          yq eval -i \
            ".users.\"$USERNAME\".aliases = [\"$ALIAS\"] |
            .users.\"$USERNAME\".emails = [\"$EMAIL\"] |
            .users.\"$USERNAME\".services.email.to = \"$EMAIL\" |
            .users.\"$USERNAME\".services.slack.to = \"@$USERNAME\"" \
            "$FILE"

          yq 'sort_keys(..) | pick(["users"] + ["services"])' -i $FILE

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          USERNAME="${{ github.event.inputs.username }}"
          git config user.name "trizbot"
          git config user.email "trizbot@org.com"
          BRANCH="add-$USERNAME-to-notifications"
          git checkout -b "$BRANCH"
          git add notifications/notifications.yaml
          git commit -m "Add $USERNAME to notifications"
          git push origin "$BRANCH"

          gh pr create --title "Add $USERNAME from origin-repo" \
                       --body "Triggered by origin-repo PR" \
                       --base main \
                       --head "$BRANCH"